$ErrorActionPreference = 'Stop'
$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$report = Get-Content (Join-Path $here 'dupart.json') -Raw -Encoding UTF8 | ConvertFrom-Json

# A name counts as the PLAIN printing when nothing is left after removing the
# bare card number the source likes to repeat: "Nami (OP15-108)" is plain,
# "Nami (OP15-108) (Dash Pack)" is not.
function Is-Plain($name) {
  $n = $name
  $n = [regex]::Replace($n, '\s*\(\s*(?:[A-Z]{1,4}\d{2}-\d{3}|\d{3})\s*\)', '')
  $n = [regex]::Replace($n, '\s*-\s*[A-Z]{1,4}\d{2}-\d{3}', '')
  $n = [regex]::Replace($n, '\s*-\s*P-\d{3}', '')
  return -not ($n -match '[\(\[]')
}

$rows = New-Object System.Collections.ArrayList
$nPlaceholder = 0; $nShared = 0

foreach ($g in $report) {
  $members = @($g.members)
  # A genuine mix-up is a pair. One file handed to dozens of cards is the
  # source's "no picture yet" placeholder, which is a different problem.
  $isPlaceholder = $members.Count -gt 5
  if ($isPlaceholder) {
    foreach ($m in $members) {
      [void]$rows.Add([pscustomobject]@{ f = ($m.url -split '/')[-1]; k = 0; o = ''; n = $m.name })
      $nPlaceholder++
    }
    continue
  }
  $plain = @($members | Where-Object { Is-Plain $_.name })
  foreach ($m in $members) {
    # The plain printing legitimately owns the artwork. Only flag it when every
    # member is a variant and there is no way to tell which is the impostor.
    if ($plain.Count -eq 1 -and $plain[0].name -eq $m.name) { continue }
    $others = (@($members | Where-Object { $_.name -ne $m.name } | ForEach-Object { $_.name }) | Sort-Object -Unique) -join ', '
    [void]$rows.Add([pscustomobject]@{ f = ($m.url -split '/')[-1]; k = 1; o = $others; n = $m.name })
    $nShared++
  }
}

$rows = $rows | Sort-Object k, n
$lines = $rows | ForEach-Object {
  "  [$(ConvertTo-Json $_.f -Compress), $($_.k), $(ConvertTo-Json $_.o -Compress)],  // $($_.n)"
}

$header = @"
/* imgflags.js — card pictures that are not the card.

   Generated by scanall.ps1 + genflags.ps1, not written by hand. Every one of
   optcgapi's 5,148 card images was fetched and MD5'd; these are the files that
   came back byte-for-byte identical to a DIFFERENT card's image. 36 clusters,
   verified $(Get-Date -Format 'yyyy-MM-dd').

   Two separate faults live in here.

   0 = no artwork at all. A single "coming soon" graphic is served, under $nPlaceholder
       different filenames, for Premium Card Collection reprints, CS 2023
       Finalist versions, Welcome Pack, Demo Deck and several DON!!. Drawing it
       is worse than drawing nothing, so the app substitutes its own placeholder.

   1 = someone else's artwork. The source keeps one picture per card NUMBER, so
       when a set holds both a plain card and a special version sharing that
       number, the special one is handed a copy of the plain picture under a
       fresh filename. The URLs differ; the bytes do not. OP-16 "Vista (TR)" is
       the case that started this — it serves the Rare art, and every plausible
       alternate filename for the real TR art 404s.

   Where exactly one card in a cluster is the plain printing, that card is left
   unflagged: the artwork is legitimately its own. Where every member carries a
   variant marker (Full Art vs Alternate Art, Pirate Foil vs Reprint, the two
   2024 Regional Finalist printings) there is no way to tell which one is the
   impostor, so both are flagged.

   None of this is fixable — the correct files are not on their server. It can
   only be reported honestly, which is what the badge does.

   Keyed on image filename, which is unique across all 5,148 and independent of
   the set_id rewriting that normaliseDons() does. Re-run scanall.ps1 when new
   sets land. */
window.IMG_FLAGS = [
"@

($header + "`n" + ($lines -join "`n") + "`n];`n") | Out-File -Encoding utf8 (Join-Path $here 'imgflags.js')
Write-Host "no-artwork: $nPlaceholder   wrong-artwork: $nShared   rows: $($rows.Count)"
