/* imgflags.js ??card pictures that are not the card.

   Generated by scanall.ps1 + genflags.ps1, not written by hand. Every one of
   optcgapi's 5,148 card images was fetched and MD5'd; these are the files that
   came back byte-for-byte identical to a DIFFERENT card's image. 36 clusters,
   verified 2026-07-27.

   Two separate faults live in here.

   0 = no artwork at all. A single "coming soon" graphic is served, under 30
       different filenames, for Premium Card Collection reprints, CS 2023
       Finalist versions, Welcome Pack, Demo Deck and several DON!!. Drawing it
       is worse than drawing nothing, so the app substitutes its own placeholder.

   1 = someone else's artwork. The source keeps one picture per card NUMBER, so
       when a set holds both a plain card and a special version sharing that
       number, the special one is handed a copy of the plain picture under a
       fresh filename. The URLs differ; the bytes do not. OP-16 "Vista (TR)" is
       the case that started this ??it serves the Rare art, and every plausible
       alternate filename for the real TR art 404s.

   Where exactly one card in a cluster is the plain printing, that card is left
   unflagged: the artwork is legitimately its own. Where every member carries a
   variant marker (Full Art vs Alternate Art, Pirate Foil vs Reprint, the two
   2024 Regional Finalist printings) there is no way to tell which one is the
   impostor, so both are flagged.

   None of this is fixable ??the correct files are not on their server. It can
   only be reported honestly, which is what the badge does.

   Keyed on image filename, which is unique across all 5,148 and independent of
   the set_id rewriting that normaliseDons() does. Re-run scanall.ps1 when new
   sets land. */
window.IMG_FLAGS = [
  ["Baby_5_Premium_Card_Collection_-Best_Selection_Vol._5-_img.jpg", 0, ""],  // Baby 5 (Premium Card Collection -Best Selection Vol. 5-)
  ["Bartolomeo_CS_2023_Event_Pack_Finalist_Ver._img.jpg", 0, ""],  // Bartolomeo (CS 2023 Event Pack Finalist Ver.)
  ["Blaze_Slice_Premium_Card_Collection_-Best_Selection_Vol._5-_img.jpg", 0, ""],  // Blaze Slice (Premium Card Collection -Best Selection Vol. 5-)
  ["DON_Card_Boa_Hancock_-_Extra_Booster_One_Piece_Heroines_Edition_EB-03_img.jpg", 0, ""],  // DON!! Card (Boa Hancock)
  ["DON_Card_Nico_Robin_-_Extra_Booster_One_Piece_Heroines_Edition_EB-03_img.jpg", 0, ""],  // DON!! Card (Nico Robin)
  ["DON_Card_Nico_Robin_Gold_-_Extra_Booster_One_Piece_Heroines_Edition_EB-03_img.jpg", 0, ""],  // DON!! Card (Nico Robin) (Gold)
  ["DON_Card_Uta_-_Extra_Booster_One_Piece_Heroines_Edition_EB-03_img.jpg", 0, ""],  // DON!! Card (Uta)
  ["Electrical_Luna_Premium_Card_Collection_-Best_Selection_Vol._5-_img.jpg", 0, ""],  // Electrical Luna (Premium Card Collection -Best Selection Vol. 5-)
  ["General_Franky_CS_2023_Event_Pack_Finalist_Ver._img.jpg", 0, ""],  // General Franky (CS 2023 Event Pack Finalist Ver.)
  ["Hair_Removal_Fist_Premium_Card_Collection_-Best_Selection_Vol._5-_img.jpg", 0, ""],  // Hair Removal Fist (Premium Card Collection -Best Selection Vol. 5-)
  ["Hina_Premium_Card_Collection_-Best_Selection_Vol._5-_img.jpg", 0, ""],  // Hina (Premium Card Collection -Best Selection Vol. 5-)
  ["Issho_Welcome_Pack_Vol._1_img.jpg", 0, ""],  // Issho (Welcome Pack Vol. 1)
  ["Jinbe_CS_2023_Event_Pack_Finalist_Ver._img.jpg", 0, ""],  // Jinbe (CS 2023 Event Pack Finalist Ver.)
  ["Kouzuki_Oden_Premium_Card_Collection_-Best_Selection_Vol._5-_img.jpg", 0, ""],  // Kouzuki Oden (Premium Card Collection -Best Selection Vol. 5-)
  ["Kuina_Premium_Card_Collection_-Best_Selection_Vol._5-_img.jpg", 0, ""],  // Kuina (Premium Card Collection -Best Selection Vol. 5-)
  ["Lets_Crash_This_Wedding_Premium_Card_Collection_-Best_Selection_Vol._5-_img.jpg", 0, ""],  // Let's Crash This Wedding!!! (Premium Card Collection -Best Selection Vol. 5-)
  ["Merry_Go_Premium_Card_Collection_-Best_Selection_Vol._5-_img.jpg", 0, ""],  // Merry Go (Premium Card Collection -Best Selection Vol. 5-)
  ["Monkey.D.Luffy_CS_2023_Event_Pack_Finalist_Ver._img.jpg", 0, ""],  // Monkey.D.Luffy (CS 2023 Event Pack Finalist Ver.)
  ["Portgas.D.Ace_CS_2023_Event_Pack_Finalist_Ver._img.jpg", 0, ""],  // Portgas.D.Ace (CS 2023 Event Pack Finalist Ver.)
  ["Raizo_CS_2023_Event_Pack_Finalist_Ver._img.jpg", 0, ""],  // Raizo (CS 2023 Event Pack Finalist Ver.)
  ["Saint_Shalria_Premium_Card_Collection_-Best_Selection_Vol._5-_img.jpg", 0, ""],  // Saint Shalria (Premium Card Collection -Best Selection Vol. 5-)
  ["Sanji_CS_2023_Event_Pack_Finalist_Ver._img.jpg", 0, ""],  // Sanji (CS 2023 Event Pack Finalist Ver.)
  ["Sanji_Demo_Deck_2023_img.jpg", 0, ""],  // Sanji (Demo Deck 2023)
  ["Satori_Welcome_Pack_Vol._1_img.jpg", 0, ""],  // Satori (Welcome Pack Vol. 1)
  ["Sengoku_CS_2023_Event_Pack_Finalist_Ver._img.jpg", 0, ""],  // Sengoku (CS 2023 Event Pack Finalist Ver.)
  ["Shakuyaku_Premium_Card_Collection_-Best_Selection_Vol._5-_img.jpg", 0, ""],  // Shakuyaku (Premium Card Collection -Best Selection Vol. 5-)
  ["Trafalgar_Law_Welcome_Pack_Vol._1_img.jpg", 0, ""],  // Trafalgar Law (Welcome Pack Vol. 1)
  ["Tsuru_CS_2023_Event_Pack_Finalist_Ver._img.jpg", 0, ""],  // Tsuru (CS 2023 Event Pack Finalist Ver.)
  ["Usopp_Demo_Deck_2023_img.jpg", 0, ""],  // Usopp (Demo Deck 2023)
  ["Uta_CS_2023_Event_Pack_Finalist_Ver._img.jpg", 0, ""],  // Uta (CS 2023 Event Pack Finalist Ver.)
  ["OP15-023_Gw7GOtl.jpg", 1, "Arlong"],  // Arlong (Dash Pack)
  ["OP04-032_p3.jpg", 1, "Baby 5 (OP04-032) (Jolly Roger Foil)"],  // Baby 5 (OP04-032) (Full Art)
  ["OP04-032_p3_0Zy6GwW.jpg", 1, "Baby 5 (OP04-032) (Full Art)"],  // Baby 5 (OP04-032) (Jolly Roger Foil)
  ["OP15-014_hYyADKn.jpg", 1, "Bartolomeo"],  // Bartolomeo (Dash Pack)
  ["OP04-089_r1_TNYzQKN.jpg", 1, "Bartolomeo"],  // Bartolomeo (OP04-089) (Reprint)
  ["ST14-010_Ge3CNVB.jpg", 1, "Brook"],  // Brook (Reprint)
  ["ST02-004_p4_M22zdUX.jpg", 1, "Capone\"Gang\"Bege (ST02-004) (Full Art)"],  // Capone"Gang"Bege (ST02-004) (Alternate Art)
  ["ST02-004_p4.jpg", 1, "Capone\"Gang\"Bege (ST02-004) (Alternate Art)"],  // Capone"Gang"Bege (ST02-004) (Full Art)
  ["OP08-023_p1.jpg", 1, "Carrot (SP)"],  // Carrot (023) (Parallel)
  ["OP08-023_p1_8FjIUrx.jpg", 1, "Carrot (023) (Parallel)"],  // Carrot (SP)
  ["OP05-114_p2.jpg", 1, "El Thor"],  // El Thor (Jolly Roger Foil)
  ["OP09-078_p1_QtJ1DiN.jpg", 1, "Gum-Gum Giant (Reprint)"],  // Gum-Gum Giant (Manga)
  ["OP09-078_p1.jpg", 1, "Gum-Gum Giant (Manga)"],  // Gum-Gum Giant (Reprint)
  ["OP01-033_p5_8AI2ZwU.jpg", 1, "Izo (OP01-033) (Full Art)"],  // Izo (OP01-033) (Alternate Art)
  ["OP01-033_p5.jpg", 1, "Izo (OP01-033) (Alternate Art)"],  // Izo (OP01-033) (Full Art)
  ["P-063_p1.jpg", 1, "Jinbe - P-063 (Pirate Foil)"],  // Jinbe - P-063 (Alternate Art)
  ["P-063_p1_rWUDzZS.jpg", 1, "Jinbe - P-063 (Alternate Art)"],  // Jinbe - P-063 (Pirate Foil)
  ["OP01-041_p5_BTppBsS.jpg", 1, "Kouzuki Momonosuke (Full Art)"],  // Kouzuki Momonosuke (Alternate Art)
  ["OP01-041_p5.jpg", 1, "Kouzuki Momonosuke (Alternate Art)"],  // Kouzuki Momonosuke (Full Art)
  ["OP15-042_8B97keJ.jpg", 1, "Kyros"],  // Kyros (Dash Pack)
  ["OP15-076_SWU4TiL.jpg", 1, "Lightning Beast Kiten"],  // Lightning Beast Kiten (Dash Pack)
  ["ST17-005_p1_rUiVDQR.jpg", 1, "Marshall.D.Teach - ST17-005"],  // Marshall.D.Teach - ST17-005 (Pirate Foil)
  ["OP05-073_p2_BpYvfDX.jpg", 1, "Miss Doublefinger(Zala) (Jolly Roger Foil)"],  // Miss Doublefinger(Zala) (Full Art)
  ["OP05-073_p2.jpg", 1, "Miss Doublefinger(Zala) (Full Art)"],  // Miss Doublefinger(Zala) (Jolly Roger Foil)
  ["OP07-014_r1_LLH4ouU.jpg", 1, "Moda (Reprint)"],  // Moda (Pirate Foil)
  ["OP07-014_r1.jpg", 1, "Moda (Pirate Foil)"],  // Moda (Reprint)
  ["OP14-074_NPJNVno.jpg", 1, "Monet"],  // Monet (Dash Pack)
  ["EB02-061_r1_87VjsGa.jpg", 1, "Monkey.D.Luffy - EB02-061 (SP)"],  // Monkey.D.Luffy - EB02-061 (Reprint)
  ["EB02-061_r1.jpg", 1, "Monkey.D.Luffy - EB02-061 (Reprint)"],  // Monkey.D.Luffy - EB02-061 (SP)
  ["P-075_r1_BCHumov.jpg", 1, "Monkey.D.Luffy - P-075 (Reprint)"],  // Monkey.D.Luffy - P-075 (Pirate Foil)
  ["P-075_r1.jpg", 1, "Monkey.D.Luffy - P-075 (Pirate Foil)"],  // Monkey.D.Luffy - P-075 (Reprint)
  ["ST29-001_IYtkmBo.jpg", 1, "Monkey.D.Luffy (001)"],  // Monkey.D.Luffy (001) (Parallel)
  ["Monkey.D.Luffy_041_Offline_Regional_2024_Vol._2_Finalist_img.jpg", 1, "Monkey.D.Luffy (041) (Online Regional 2024 Vol. 2) [Finalist]"],  // Monkey.D.Luffy (041) (Offline Regional 2024 Vol. 2) [Finalist]
  ["Monkey.D.Luffy_041_Online_Regional_2024_Vol._2_Finalist_img.jpg", 1, "Monkey.D.Luffy (041) (Offline Regional 2024 Vol. 2) [Finalist]"],  // Monkey.D.Luffy (041) (Online Regional 2024 Vol. 2) [Finalist]
  ["EB01-018_r1_8aijthW.jpg", 1, "Mountain God (Reprint)"],  // Mountain God (Pirate Foil)
  ["EB01-018_r1.jpg", 1, "Mountain God (Pirate Foil)"],  // Mountain God (Reprint)
  ["OP15-108_3uuMAJI.jpg", 1, "Nami (OP15-108)"],  // Nami (OP15-108) (Dash Pack)
  ["P-074_r1_oFjlIxa.jpg", 1, "Portgas.D.Ace - P-074 (Reprint)"],  // Portgas.D.Ace - P-074 (Pirate Foil)
  ["P-074_r1.jpg", 1, "Portgas.D.Ace - P-074 (Pirate Foil)"],  // Portgas.D.Ace - P-074 (Reprint)
  ["OP05-091_p1.jpg", 1, "Rebecca (SP)"],  // Rebecca (Alternate Art)
  ["OP05-091_p1_LMalLg1.jpg", 1, "Rebecca (Alternate Art)"],  // Rebecca (SP)
  ["P-073_r1_KXa64g5.jpg", 1, "Sabo - P-073 (Reprint)"],  // Sabo - P-073 (Pirate Foil)
  ["P-073_r1.jpg", 1, "Sabo - P-073 (Pirate Foil)"],  // Sabo - P-073 (Reprint)
  ["Sasaki_CS_2023_Event_Pack_Finalist_Ver._img.jpg", 1, "Sasaki (CS 2023 Event Pack)"],  // Sasaki (CS 2023 Event Pack Finalist Ver.)
  ["Sasaki_CS_2023_Event_Pack_img.jpg", 1, "Sasaki (CS 2023 Event Pack Finalist Ver.)"],  // Sasaki (CS 2023 Event Pack)
  ["OP16-108_iwCfr1w.jpg", 1, "Shiryu"],  // Shiryu (Full Art)
  ["OP13-084_4G64N0X.jpg", 1, "St. Shepherd Ju Peter"],  // St. Shepherd Ju Peter (Parallel)
  ["OP10-018_OO8g5lU.jpg", 1, "Ten-Layer Igloo"],  // Ten-Layer Igloo (Pirate Foil)
  ["OP10-119_p1_sEtXfvx.jpg", 1, "Trafalgar Law (119) (Parallel)"],  // Trafalgar Law - OP10-119 (SP)
  ["OP10-119_p1.jpg", 1, "Trafalgar Law - OP10-119 (SP)"],  // Trafalgar Law (119) (Parallel)
  ["Trafalgar_Law_Offline_Regional_2024_Vol._2_Finalist_img.jpg", 1, "Trafalgar Law (Online Regional 2024 Vol. 2) [Finalist]"],  // Trafalgar Law (Offline Regional 2024 Vol. 2) [Finalist]
  ["Trafalgar_Law_Online_Regional_2024_Vol._2_Finalist_img.jpg", 1, "Trafalgar Law (Offline Regional 2024 Vol. 2) [Finalist]"],  // Trafalgar Law (Online Regional 2024 Vol. 2) [Finalist]
  ["OP06-063_r1_gDLU3wS.jpg", 1, "Vinsmoke Sora (Reprint)"],  // Vinsmoke Sora (Pirate Foil)
  ["OP06-063_r1.jpg", 1, "Vinsmoke Sora (Pirate Foil)"],  // Vinsmoke Sora (Reprint)
  ["OP16-011_l76oKss.jpg", 1, "Vista"],  // Vista (TR)
];

